---
- name: Restart guides Deployment Pod
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Restart Deployment by updating annotations
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: guides
        namespace: infra
        definition:
          metadata:
            annotations:
              kubernetes.io/change-cause: "Restarted at {{ ansible_date_time.iso8601 }}"
      register: restart_result

    - name: Display result
      debug:
        var: restart_result
