---
- name: Restart Poestore PostgreSQL Pod
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Restart DeploymentConfig by updating spec.template.metadata.annotations
      kubernetes.core.k8s:
        api_version: apps.openshift.io/v1
        kind: DeploymentConfig
        name: postgresql
        namespace: petstore
        definition:
          spec:
            template:
              metadata:
                annotations:
                  openshift.io/change-cause: "Restarted at {{ ansible_date_time.iso8601 }}"

      register: restart_result

    - name: Display result
      debug:
        var: restart_result
