---
- name: Restart PostgreSQL Pods
  hosts: all
  tasks:
    - name: Set OpenShift project
      command: oc project petstore
      register: project_result
      failed_when: "'error' in project_result.stderr"
      changed_when: False

    - name: Restart DeploymentConfig
      command: oc rollout restart dc/postgresql -n petstore
      register: restart_result
      failed_when: "'error' in restart_result.stderr"

    - name: Wait for DeploymentConfig to be available
      command: oc wait --for=condition=available dc/postgresql --timeout=300s -n petstore
      register: wait_result
      failed_when: "'error' in wait_result.stderr"

    - name: Get Pod status
      command: oc get pods -l name=postgresql -n petstore
      register: pods_result
      failed_when: "'error' in pods_result.stderr"
      changed_when: False

    - name: Show Pods Status
      debug:
        msg: "{{ pods_result.stdout }}"
